// src/styles/globalStyles.js
import { StyleSheet } from 'react-native';

export const globalStyles = StyleSheet.create({
  // App Container
  app: {
    flex: 1,
    backgroundColor: '#ffffff',
  },
  container: {
    flex: 1,
    backgroundColor: '#f0f9ff',
  },
  scrollView: {
    flex: 1,
  },

  // Header Styles
  header: {
    backgroundColor: '#ffffff',
    padding: 24,
    marginBottom: 24,
    borderBottomLeftRadius: 24,
    borderBottomRightRadius: 24,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  headerTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#1f2937',
  },
  headerSubtitle: {
    fontSize: 16,
    color: '#6b7280',
    marginTop: 4,
  },
  headerIcon: {
    backgroundColor: '#3b82f6',
    padding: 12,
    borderRadius: 50,
  },

  // Simple Header Styles
  simpleHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 24,
    backgroundColor: '#ffffff',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  simpleHeaderTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#1f2937',
  },

  // Stats Container and Cards
  statsContainer: {
    paddingHorizontal: 24,
    marginBottom: 24,
  },
  statsGrid: {
    flexDirection: 'row',
    gap: 16,
  },
  statCard: {
    flex: 1,
    backgroundColor: '#ffffff',
    padding: 16,
    borderRadius: 16,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  statContent: {
    flex: 1,
  },
  statLabel: {
    fontSize: 14,
    color: '#6b7280',
    marginBottom: 4,
  },
  statValue: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#1f2937',
  },

  // Analytics Stat Cards
  statCardTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1f2937',
    marginBottom: 8,
  },
  statCardValue: {
    fontSize: 24,
    fontWeight: 'bold',
    marginBottom: 4,
  },
  statCardUnit: {
    fontSize: 12,
    color: '#6b7280',
  },

  // Section Styles
  section: {
    paddingHorizontal: 24,
    marginBottom: 24,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#1f2937',
    marginBottom: 16,
  },

  // Button Styles
  primaryButton: {
    backgroundColor: '#3b82f6',
    padding: 16,
    borderRadius: 16,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
    shadowColor: '#3b82f6',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 6,
  },
  buttonContent: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  primaryButtonText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '600',
    marginLeft: 12,
  },
  secondaryButton: {
    backgroundColor: '#ffffff',
    padding: 16,
    borderRadius: 16,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  secondaryButtonText: {
    color: '#374151',
    fontSize: 16,
    fontWeight: '600',
    marginLeft: 12,
  },

  // Icon Styles
  cowIcon: {
    fontSize: 24,
  },

  // Result Card Styles
  resultCard: {
    backgroundColor: '#ffffff',
    padding: 16,
    borderRadius: 12,
    marginBottom: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  resultContent: {
    flex: 1,
  },
  resultCowId: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1f2937',
    marginBottom: 4,
  },
  resultDensity: {
    fontSize: 14,
    color: '#6b7280',
  },

  // Quality Badge Styles
  qualityBadge: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
  },
  qualityText: {
    fontSize: 14,
    fontWeight: '500',
  },
  excellentBadge: {
    backgroundColor: '#d1fae5',
  },
  excellentText: {
    color: '#059669',
  },
  goodBadge: {
    backgroundColor: '#dbeafe',
  },
  goodText: {
    color: '#2563eb',
  },
  fairBadge: {
    backgroundColor: '#fef3c7',
  },
  fairText: {
    color: '#d97706',
  },
  defaultBadge: {
    backgroundColor: '#f3f4f6',
  },
  defaultText: {
    color: '#6b7280',
  },

  // Scan Screen Styles
  scanContainer: {
    flex: 1,
    backgroundColor: '#111827',
  },
  scanHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 24,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  scanHeaderTitle: {
    color: '#ffffff',
    fontSize: 18,
    fontWeight: '600',
  },
  cameraContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#1f2937',
  },
  cameraContent: {
    alignItems: 'center',
  },
  cameraFrame: {
    width: 200,
    height: 200,
    borderWidth: 4,
    borderColor: '#ffffff',
    borderStyle: 'dashed',
    borderRadius: 24,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 24,
  },
  cameraText: {
    color: '#ffffff',
    fontSize: 18,
    marginBottom: 24,
    textAlign: 'center',
  },
  scanButton: {
    backgroundColor: '#3b82f6',
    paddingHorizontal: 32,
    paddingVertical: 12,
    borderRadius: 25,
  },
  scanButtonText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '600',
  },
  scanningContent: {
    alignItems: 'center',
  },
  scanningFrame: {
    width: 200,
    height: 200,
    borderWidth: 4,
    borderColor: '#3b82f6',
    borderRadius: 24,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 24,
  },
  scanningText: {
    color: '#ffffff',
    fontSize: 18,
    marginBottom: 8,
  },
  scanningSubtext: {
    color: '#93c5fd',
    fontSize: 16,
  },
  instructionsContainer: {
    padding: 24,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  instructionsCard: {
    backgroundColor: 'rgba(59, 130, 246, 0.2)',
    padding: 16,
    borderRadius: 12,
  },
  instructionsText: {
    color: '#93c5fd',
    fontSize: 14,
    textAlign: 'center',
  },

  // Detail Card Styles (Results Screen)
  detailCard: {
    backgroundColor: '#ffffff',
    margin: 24,
    padding: 24,
    borderRadius: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 4,
  },
  detailHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 16,
  },
  detailTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#1f2937',
    marginBottom: 8,
  },
  timestampContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  timestamp: {
    fontSize: 14,
    color: '#6b7280',
    marginLeft: 4,
  },

  // Metrics Grid Styles
  metricsGrid: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginBottom: 16,
  },
  metric: {
    alignItems: 'center',
  },
  metricValue: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#3b82f6',
    marginBottom: 4,
  },
  metricLabel: {
    fontSize: 12,
    color: '#6b7280',
    textAlign: 'center',
  },

  // Analysis Card Styles
  analysisCard: {
    backgroundColor: '#f9fafb',
    padding: 16,
    borderRadius: 12,
  },
  analysisTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1f2937',
    marginBottom: 8,
  },
  analysisContent: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  analysisText: {
    fontSize: 14,
    color: '#374151',
    marginLeft: 8,
    flex: 1,
  },

  // Chart Card Styles (Analytics Screen)
  chartCard: {
    backgroundColor: '#ffffff',
    margin: 24,
    marginTop: 0,
    padding: 24,
    borderRadius: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  chartTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1f2937',
    marginBottom: 16,
  },
  distributionItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  distributionLabel: {
    fontSize: 14,
    color: '#374151',
    width: 80,
  },
  distributionBar: {
    flex: 1,
    height: 8,
    backgroundColor: '#e5e7eb',
    borderRadius: 4,
    marginHorizontal: 16,
  },
  distributionFill: {
    height: 8,
    borderRadius: 4,
  },
  distributionValue: {
    fontSize: 14,
    color: '#6b7280',
    width: 40,
    textAlign: 'right',
  },

  // Recommendations Card Styles
  recommendationsCard: {
    backgroundColor: '#ffffff',
    margin: 24,
    marginTop: 0,
    padding: 24,
    borderRadius: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  recommendationsTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1f2937',
    marginBottom: 16,
  },
  recommendation: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 12,
  },
  recommendationIcon: {
    backgroundColor: '#f0f9ff',
    padding: 8,
    borderRadius: 20,
    marginRight: 12,
    marginTop: 2,
  },
  recommendationContent: {
    flex: 1,
  },
  recommendationTitle: {
    fontSize: 16,
    fontWeight: '500',
    color: '#1f2937',
    marginBottom: 2,
  },
  recommendationDescription: {
    fontSize: 14,
    color: '#6b7280',
  },

  // Cow Management Screen Styles
  cowCard: {
    backgroundColor: '#ffffff',
    marginHorizontal: 24,
    marginBottom: 16,
    padding: 16,
    borderRadius: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  cowContent: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  cowIconContainer: {
    backgroundColor: '#dbeafe',
    padding: 12,
    borderRadius: 20,
    marginRight: 16,
  },
  cowEmoji: {
    fontSize: 24,
  },
  cowInfo: {
    flex: 1,
  },
  cowId: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1f2937',
    marginBottom: 4,
  },
  cowLastTest: {
    fontSize: 14,
    color: '#6b7280',
  },

  // Bottom Navigation Styles
  bottomNav: {
    backgroundColor: '#ffffff',
    borderTopWidth: 1,
    borderTopColor: '#e5e7eb',
    paddingHorizontal: 24,
    paddingVertical: 16,
    flexDirection: 'row',
    justifyContent: 'space-around',
  },
  navItem: {
    alignItems: 'center',
  },
  navLabel: {
    fontSize: 12,
    marginTop: 4,
  },
  navEmoji: {
    fontSize: 24,
  },

  // Splash Screen Styles
  splashContainer: {
    flex: 1,
    backgroundColor: '#1e40af',
    justifyContent: 'center',
    alignItems: 'center',
  },
  logoContainer: {
    marginBottom: 40,
  },
  logo: {
    width: 120,
    height: 120,
    backgroundColor: '#3b82f6',
    borderRadius: 60,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.3,
    shadowRadius: 20,
    elevation: 10,
  },
  splashTitle: {
    fontSize: 32,
    fontWeight: 'bold',
    color: '#ffffff',
    marginBottom: 8,
    textAlign: 'center',
  },
  splashSubtitle: {
    fontSize: 18,
    color: '#93c5fd',
    textAlign: 'center',
  },

  // Loading Screen Styles
  loadingContainer: {
    flex: 1,
    backgroundColor: '#1e40af',
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingContent: {
    alignItems: 'center',
    paddingHorizontal: 40,
  },
  loadingLogo: {
    width: 80,
    height: 80,
    backgroundColor: '#3b82f6',
    borderRadius: 40,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 30,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 6,
  },
  loadingTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#ffffff',
    marginBottom: 8,
    textAlign: 'center',
  },
  loadingSubtitle: {
    fontSize: 16,
    color: '#93c5fd',
    textAlign: 'center',
    marginBottom: 40,
  },
  loadingDotsContainer: {
    flexDirection: 'row',
    marginBottom: 40,
  },
  loadingDot: {
    width: 12,
    height: 12,
    backgroundColor: '#ffffff',
    borderRadius: 6,
    marginHorizontal: 4,
  },
  loadingSteps: {
    alignItems: 'flex-start',
  },
  loadingStep: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  loadingStepText: {
    color: '#ffffff',
    fontSize: 14,
    marginLeft: 8,
  },

  // Sensor Monitoring Screen Styles
  controlPanel: {
    backgroundColor: '#ffffff',
    margin: 24,
    padding: 24,
    borderRadius: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  controlPanelTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#1f2937',
    marginBottom: 16,
  },
  controlButtons: {
    marginBottom: 16,
  },
  startMonitoringButton: {
    backgroundColor: '#10b981',
    padding: 16,
    borderRadius: 12,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#10b981',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
  },
  startMonitoringText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '600',
    marginLeft: 8,
  },
  stopMonitoringButton: {
    backgroundColor: '#ef4444',
    padding: 16,
    borderRadius: 12,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#ef4444',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
  },
  stopMonitoringText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '600',
    marginLeft: 8,
  },
  monitoringIndicator: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#f0fdf4',
    padding: 12,
    borderRadius: 8,
  },
  blinkingDot: {
    width: 8,
    height: 8,
    backgroundColor: '#10b981',
    borderRadius: 4,
    marginRight: 8,
  },
  monitoringText: {
    color: '#059669',
    fontSize: 14,
    fontWeight: '500',
  },
  sensorGrid: {
    paddingHorizontal: 24,
    marginBottom: 24,
  },
  sensorCard: {
    backgroundColor: '#ffffff',
    padding: 20,
    borderRadius: 16,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 3,
  },
  sensorHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  sensorTitleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  sensorTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1f2937',
    marginLeft: 8,
  },
  sensorStatus: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
  },
  sensorStatusText: {
    fontSize: 12,
    fontWeight: '500',
    marginLeft: 4,
  },
  sensorValueContainer: {
    flexDirection: 'row',
    alignItems: 'baseline',
    marginBottom: 8,
  },
  sensorValue: {
    fontSize: 32,
    fontWeight: 'bold',
    color: '#1f2937',
  },
  sensorUnit: {
    fontSize: 16,
    color: '#6b7280',
    marginLeft: 4,
  },
  sensorLastUpdate: {
    fontSize: 12,
    color: '#9ca3af',
    fontStyle: 'italic',
  },
  systemStatus: {
    backgroundColor: '#ffffff',
    marginHorizontal: 24,
    marginBottom: 24,
    padding: 20,
    borderRadius: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 3,
  },
  systemStatusTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1f2937',
    marginBottom: 16,
  },
  statusItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  statusText: {
    fontSize: 14,
    color: '#374151',
    marginLeft: 8,
  },
  calibrationInfo: {
    backgroundColor: '#ffffff',
    marginHorizontal: 24,
    marginBottom: 24,
    padding: 20,
    borderRadius: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 3,
  },
  calibrationTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1f2937',
    marginBottom: 12,
  },
  calibrationText: {
    fontSize: 14,
    color: '#6b7280',
    marginBottom: 8,
  },
  calibrateButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#eff6ff',
    padding: 12,
    borderRadius: 8,
    marginTop: 8,
    alignSelf: 'flex-start',
  },
  calibrateButtonText: {
    fontSize: 14,
    color: '#3b82f6',
    fontWeight: '500',
    marginLeft: 4,
  },
  // Add these styles to your existing globalStyles.js file

// Historic Screen Styles
searchContainer: {
  backgroundColor: '#ffffff',
  paddingHorizontal: 24,
  paddingVertical: 16,
  shadowColor: '#000',
  shadowOffset: { width: 0, height: 1 },
  shadowOpacity: 0.05,
  shadowRadius: 2,
  elevation: 1,
},
searchInputContainer: {
  flexDirection: 'row',
  alignItems: 'center',
  backgroundColor: '#f9fafb',
  borderRadius: 12,
  paddingHorizontal: 16,
  paddingVertical: 12,
  marginBottom: 16,
},
searchInput: {
  flex: 1,
  fontSize: 16,
  color: '#1f2937',
  marginLeft: 8,
},
filterScroll: {
  marginBottom: 8,
},
filterChip: {
  flexDirection: 'row',
  alignItems: 'center',
  backgroundColor: '#f3f4f6',
  paddingHorizontal: 16,
  paddingVertical: 8,
  borderRadius: 20,
  marginRight: 8,
},
filterChipActive: {
  backgroundColor: '#3b82f6',
},
filterChipText: {
  fontSize: 14,
  color: '#6b7280',
  marginLeft: 4,
  fontWeight: '500',
},
filterChipTextActive: {
  color: '#ffffff',
},
statsContainer: {
  flexDirection: 'row',
  backgroundColor: '#ffffff',
  marginHorizontal: 24,
  marginBottom: 16,
  padding: 20,
  borderRadius: 16,
  shadowColor: '#000',
  shadowOffset: { width: 0, height: 2 },
  shadowOpacity: 0.1,
  shadowRadius: 6,
  elevation: 3,
},
statItem: {
  flex: 1,
  alignItems: 'center',
},
statNumber: {
  fontSize: 24,
  fontWeight: 'bold',
  color: '#1f2937',
  marginBottom: 4,
},
statLabel: {
  fontSize: 12,
  color: '#6b7280',
  textAlign: 'center',
},
measurementCard: {
  backgroundColor: '#ffffff',
  marginHorizontal: 24,
  marginBottom: 16,
  borderRadius: 16,
  shadowColor: '#000',
  shadowOffset: { width: 0, height: 2 },
  shadowOpacity: 0.1,
  shadowRadius: 6,
  elevation: 3,
  overflow: 'hidden',
},
measurementHeader: {
  flexDirection: 'row',
  justifyContent: 'space-between',
  alignItems: 'flex-start',
  padding: 20,
  paddingBottom: 16,
},
measurementCowId: {
  fontSize: 18,
  fontWeight: 'bold',
  color: '#1f2937',
  marginBottom: 4,
},
measurementDate: {
  fontSize: 14,
  color: '#6b7280',
},
measurementActions: {
  flexDirection: 'row',
  alignItems: 'center',
},
deleteButton: {
  padding: 8,
  marginLeft: 8,
},
measurementData: {
  paddingHorizontal: 20,
  paddingBottom: 20,
},
dataRow: {
  flexDirection: 'row',
  marginBottom: 16,
},
dataItem: {
  flex: 1,
  flexDirection: 'row',
  alignItems: 'center',
},
dataLabel: {
  fontSize: 12,
  color: '#6b7280',
  marginLeft: 8,
  marginRight: 4,
},
dataValue: {
  fontSize: 16,
  fontWeight: '600',
  color: '#1f2937',
  marginLeft: 'auto',
},
emptyState: {
  alignItems: 'center',
  justifyContent: 'center',
  padding: 40,
  marginTop: 60,
},
emptyStateTitle: {
  fontSize: 20,
  fontWeight: '600',
  color: '#374151',
  marginTop: 16,
  marginBottom: 8,
},
emptyStateText: {
  fontSize: 16,
  color: '#6b7280',
  textAlign: 'center',
  lineHeight: 24,
},
bottomActions: {
  backgroundColor: '#ffffff',
  paddingHorizontal: 24,
  paddingVertical: 16,
  borderTopWidth: 1,
  borderTopColor: '#e5e7eb',
},
clearAllButton: {
  flexDirection: 'row',
  alignItems: 'center',
  justifyContent: 'center',
  backgroundColor: '#fef2f2',
  padding: 16,
  borderRadius: 12,
  borderWidth: 1,
  borderColor: '#fecaca',
},
clearAllText: {
  fontSize: 16,
  color: '#ef4444',
  fontWeight: '600',
  marginLeft: 8,
},
analytics: {
    screen: {
      flex: 1,
      backgroundColor: '#f1f5f9',
    },
    scrollView: {
      flex: 1,
      paddingBottom: 300,
    },
    emptyContainer: {
      backgroundColor: '#ffffff',
      marginHorizontal: 24,
      borderRadius: 24,
      padding: 40,
      alignItems: 'center',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.12,
      shadowRadius: 24,
      elevation: 8,
    },
    emptyIconContainer: {
      backgroundColor: '#f3f4f6',
      padding: 20,
      borderRadius: 20,
      marginBottom: 20,
    },
    emptyTitle: {
      fontSize: 20,
      fontWeight: '700',
      color: '#374151',
      marginBottom: 8,
    },
    emptyText: {
      fontSize: 14,
      color: '#6b7280',
      textAlign: 'center',
      lineHeight: 20,
    },
  },

  // Header Styles
  header: {
    container: {
      backgroundColor: '#ffffff',
      paddingHorizontal: 24,
      paddingVertical: 20,
      borderBottomLeftRadius: 24,
      borderBottomRightRadius: 24,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.08,
      shadowRadius: 12,
      elevation: 4,
    },
    inner: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 4,
    },
    iconContainer: {
      backgroundColor: '#3b82f615',
      padding: 8,
      borderRadius: 12,
      marginRight: 12,
    },
    title: {
      fontSize: 24,
      fontWeight: '800',
      color: '#1e293b',
    },
    subtitle: {
      fontSize: 14,
      color: '#64748b',
      fontWeight: '500',
      textAlign: 'center',
    },
  },

  // Filter Styles
  filter: {
    container: {
      backgroundColor: '#ffffff',
      borderRadius: 20,
      padding: 20,
      marginBottom: 16,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.08,
      shadowRadius: 12,
      elevation: 4,
    },
    title: {
      fontSize: 16,
      fontWeight: '700',
      color: '#374151',
      marginBottom: 16,
    },
    button: {
      paddingHorizontal: 20,
      paddingVertical: 12,
      borderRadius: 16,
      backgroundColor: '#ffffff',
      borderWidth: 2,
      borderColor: '#e2e8f0',
      marginHorizontal: 4,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 2,
      flexDirection: 'row',
      alignItems: 'center',
    },
    buttonSelected: {
      backgroundColor: '#3b82f6',
      borderColor: '#3b82f6',
      shadowColor: '#3b82f6',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 8,
      elevation: 6,
    },
    buttonText: {
      color: '#475569',
      fontSize: 14,
      fontWeight: '700',
    },
    buttonTextSelected: {
      color: '#ffffff',
    },
  },

  // Stat Card Styles
  statCard: {
    container: {
      backgroundColor: '#ffffff',
      borderRadius: 20,
      padding: 20,
      margin: 6,
      flex: 1,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.12,
      shadowRadius: 20,
      elevation: 8,
      borderWidth: 2,
      borderColor: 'rgba(59, 130, 246, 0.125)',
    },
    accent: {
      position: 'absolute',
      top: 0,
      right: 0,
      width: 60,
      height: 60,
      backgroundColor: 'rgba(59, 130, 246, 0.05)',
      borderRadius: 30,
      transform: [{ translateX: 15 }, { translateY: -15 }],
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 12,
    },
    iconContainer: {
      backgroundColor: 'rgba(59, 130, 246, 0.08)',
      padding: 10,
      borderRadius: 14,
      marginRight: 10,
    },
    title: {
      fontSize: 14,
      fontWeight: '700',
      color: '#374151',
      flex: 1,
    },
    value: {
      fontSize: 28,
      fontWeight: '800',
      color: '#1f2937',
      marginBottom: 4,
    },
    unit: {
      fontSize: 14,
      color: '#3b82f6',
      fontWeight: '600',
      marginBottom: 8,
    },
    trendContainer: {
      backgroundColor: '#f8fafc',
      paddingHorizontal: 10,
      paddingVertical: 6,
      borderRadius: 10,
    },
    trendText: {
      fontSize: 11,
      color: '#64748b',
      fontWeight: '600',
    },
  },

  // Chart Styles
  chart: {
    container: {
      backgroundColor: '#ffffff',
      marginHorizontal: 24,
      marginBottom: 24,
      borderRadius: 24,
      padding: 24,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.12,
      shadowRadius: 24,
      elevation: 8,
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 20,
    },
    iconContainer: {
      backgroundColor: 'rgba(59, 130, 246, 0.08)',
      padding: 12,
      borderRadius: 16,
      marginRight: 12,
    },
    title: {
      fontSize: 18,
      fontWeight: '800',
      color: '#1f2937',
      marginBottom: 2,
    },
    subtitle: {
      fontSize: 14,
      color: '#6b7280',
      fontWeight: '500',
    },
    chartArea: {
      width: '100%',
      height: 200,
      backgroundColor: '#f8fafc',
      borderRadius: 16,
      position: 'relative',
      overflow: 'hidden',
    },
    gridLine: {
      position: 'absolute',
      left: 24,
      right: 24,
      height: 1,
      backgroundColor: '#e2e8f0',
      opacity: 0.6,
    },
    dot: {
      position: 'absolute',
      width: 12,
      height: 12,
      backgroundColor: '#3b82f6',
      borderRadius: 6,
      borderWidth: 3,
      borderColor: '#ffffff',
      shadowColor: '#3b82f6',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 8,
      elevation: 4,
    },
    yAxisLabel: {
      position: 'absolute',
      fontSize: 10,
      color: '#64748b',
      fontWeight: '600',
      textAlign: 'right',
    },
    summary: {
      flexDirection: 'row',
      justifyContent: 'space-around',
      marginTop: 20,
      paddingTop: 20,
      borderTopWidth: 1,
      borderTopColor: '#f1f5f9',
    },
    summaryItem: {
      alignItems: 'center',
    },
    summaryBadge: {
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 12,
      marginBottom: 6,
    },
    summaryValue: {
      fontSize: 18,
      fontWeight: '800',
    },
    summaryLabel: {
      fontSize: 12,
      color: '#6b7280',
      fontWeight: '500',
    },
  },

  // Stats Table Styles
  statsTable: {
    container: {
      backgroundColor: '#ffffff',
      marginHorizontal: 24,
      marginBottom: 24,
      borderRadius: 24,
      padding: 24,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.12,
      shadowRadius: 24,
      elevation: 8,
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 24,
    },
    iconContainer: {
      backgroundColor: 'rgba(99, 102, 241, 0.08)',
      padding: 12,
      borderRadius: 16,
      marginRight: 12,
    },
    title: {
      fontSize: 20,
      fontWeight: '800',
      color: '#1f2937',
    },
    headerRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: 20,
      backgroundColor: '#f8fafc',
      padding: 16,
      borderRadius: 16,
    },
    headerText: {
      fontSize: 16,
      fontWeight: '700',
      color: '#374151',
    },
    dataRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      paddingVertical: 16,
      borderBottomWidth: 1,
      borderBottomColor: '#f1f5f9',
      alignItems: 'center',
    },
    parameter: {
      flexDirection: 'row',
      alignItems: 'center',
      flex: 1,
    },
    parameterIcon: {
      backgroundColor: 'rgba(59, 130, 246, 0.08)',
      padding: 6,
      borderRadius: 10,
      marginRight: 10,
    },
    parameterText: {
      fontSize: 14,
      color: '#374151',
      fontWeight: '600',
    },
    valueText: {
      fontSize: 14,
      color: '#6b7280',
      fontWeight: '600',
      textAlign: 'center',
    },
  },
});
